import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
  _AppLocalizationsDelegate();

  static Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'appTitle': 'CliniX',
      'slogan': 'Engineered For Outages, Built For Lives!',
      'selectRole': 'Select Your Role',
      'admin': 'Administrator',
      'doctor': 'Doctor',
      'nurse': 'Nurse',
      'technician': 'Technician',
      'user': 'User',
      'loginTitle': 'CliniX Login',
      'username': 'Username',
      'password': 'Password',
      'login': 'LOG IN',
      'forgotPassword': 'Forgot password?',
      'changeRole': 'Change Role',
      'haveAccount': 'Already have an account? Sign in',
      'dashboard': 'Dashboard',
      'battery': 'Battery',
      'logData': 'Log Data',
      'settings': 'Settings',
      'logout': 'Logout',
      'systemSettings': 'System Settings',
      'sourceInUse': 'Source in Use',
      'grid': 'Grid',
      'voltage': 'Voltage (V)',
      'updated': 'Updated',
      'batteryCharge': 'Battery Charge',
      'backupTime': 'Predicted Backup Time',
      'usageHistory': 'Source Usage History',
      'appearance': 'Appearance',
      'darkMode': 'Dark Mode',
      'language': 'Language',
      'account': 'Account',
      'editProfile': 'Edit Profile',
      'changePassword': 'Change Password',
      'notifications': 'Notification Settings',
      'about': 'About',
      'appVersion': 'App Version',
      'help': 'Help & Support',
      'privacy': 'Privacy Policy',
    },
    'hi': {
      'appTitle': 'क्लिनिक्स',
      'slogan': 'बिजली कटौती के लिए इंजीनियर, जीवन के लिए निर्मित!',
      'selectRole': 'अपनी भूमिका चुनें',
      'admin': 'प्रशासक',
      'doctor': 'डॉक्टर',
      'nurse': 'नर्स',
      'technician': 'तकनीशियन',
      'user': 'उपयोगकर्ता',
      'loginTitle': 'क्लिनिक्स लॉगिन',
      'username': 'उपयोगकर्ता नाम',
      'password': 'पासवर्ड',
      'login': 'लॉग इन',
      'forgotPassword': 'पासवर्ड भूल गए?',
      'changeRole': 'भूमिका बदलें',
      'haveAccount': 'पहले से खाता है? साइन इन',
      'dashboard': 'डैशबोर्ड',
      'battery': 'बैटरी',
      'logData': 'लॉग डेटा',
      'settings': 'सेटिंग्स',
      'logout': 'लॉगआउट',
      'systemSettings': 'सिस्टम सेटिंग्स',
      'sourceInUse': 'उपयोग में स्रोत',
      'grid': 'ग्रिड',
      'voltage': 'वोल्टेज (V)',
      'updated': 'अपडेटेड',
      'batteryCharge': 'बैटरी चार्ज',
      'backupTime': 'अनुमानित बैकअप समय',
      'usageHistory': 'स्रोत उपयोग इतिहास',
      'appearance': 'उपस्थिति',
      'darkMode': 'डार्क मोड',
      'language': 'भाषा',
      'account': 'खाता',
      'editProfile': 'प्रोफाइल संपादित',
      'changePassword': 'पासवर्ड बदलें',
      'notifications': 'सूचना सेटिंग्स',
      'about': 'के बारे में',
      'appVersion': 'ऐप संस्करण',
      'help': 'सहायता और समर्थन',
      'privacy': 'गोपनीयता नीति',
    },
    'ta': {
      'appTitle': 'கிளினிக்ஸ்',
      'slogan': 'மின்னணு தடங்கல்களுக்காக வடிவமைக்கப்பட்டது, வாழ்க்கைக்காக கட்டப்பட்டது!',
      'selectRole': 'உங்கள் பங்கைத் தேர்ந்தெடுக்கவும்',
      'admin': 'நிர்வாகி',
      'doctor': 'டாக்டர்',
      'nurse': 'நர்ஸ்',
      'technician': 'தொழில்நுட்ப வல்லுநர்',
      'user': 'பயனர்',
      'loginTitle': 'கிளினிக்ஸ் உள்நுழைவு',
      'username': 'பயனர் பெயர்',
      'password': 'கடவுச்சொல்',
      'login': 'உள்நுழைக',
      'forgotPassword': 'கடவுச்சொல் மறந்துவிட்டீர்களா?',
      'changeRole': 'பங்கை மாற்று',
      'haveAccount': 'ஏற்கனவே கணக்கு உள்ளதா? உள்நுழைக',
      'dashboard': 'டாஷ்போர்டு',
      'battery': 'பேட்டரி',
      'logData': 'பதிவு தரவு',
      'settings': 'அமைப்புகள்',
      'logout': 'வெளியேறு',
      'systemSettings': 'கணினி அமைப்புகள்',
      'sourceInUse': 'பயன்பாட்டில் உள்ள மூலம்',
      'grid': 'கிரிட்',
      'voltage': 'வோல்டேஜ் (V)',
      'updated': 'புதுப்பிக்கப்பட்டது',
      'batteryCharge': 'பேட்டரி சார்ஜ்',
      'backupTime': 'எதிர்பார்க்கப்படும் காப்பு நேரம்',
      'usageHistory': 'மூல பயன்பாட்டு வரலாறு',
      'appearance': 'தோற்றம்',
      'darkMode': 'இருண்ட முறை',
      'language': 'மொழி',
      'account': 'கணக்கு',
      'editProfile': 'சுயவிவரத்தைத் திருத்து',
      'changePassword': 'கடவுச்சொல்லை மாற்று',
      'notifications': 'அறிவிப்பு அமைப்புகள்',
      'about': 'பற்றி',
      'appVersion': 'பயன்பாடு பதிப்பு',
      'help': 'உதவி மற்றும் ஆதரவு',
      'privacy': 'தனியுரிமைக் கொள்கை',
    },
    'te': {
      'appTitle': 'క్లినిక్స్',
      'slogan': 'విద్యుత్ అంతరాయాల కోసం ఇంజనీర్, జీవితాల కోసం నిర్మించబడింది!',
      'selectRole': 'మీ పాత్రను ఎంచుకోండి',
      'admin': 'నిర్వాహకుడు',
      'doctor': 'డాక్టర్',
      'nurse': 'నర్స్',
      'technician': 'టెక్నీషియన్',
      'user': 'వినియోగదారు',
      'loginTitle': 'క్లినిక్స్ లాగిన్',
      'username': 'వినియోగదారు పేరు',
      'password': 'పాస్వర్డ్',
      'login': 'లాగిన్',
      'forgotPassword': 'పాస్వర్డ్ మర్చిపోయారా?',
      'changeRole': 'పాత్ర మార్చు',
      'haveAccount': 'ఇప్పటికే ఖాతా ఉందా? సైన్ ఇన్',
      'dashboard': 'డాష్బోర్డ్',
      'battery': 'బ్యాటరీ',
      'logData': 'లాగ్ డేటా',
      'settings': 'సెట్టింగులు',
      'logout': 'లాగ్అవుట్',
      'systemSettings': 'సిస్టమ్ సెట్టింగులు',
      'sourceInUse': 'ఉపయోగంలో ఉన్న మూలం',
      'grid': 'గ్రిడ్',
      'voltage': 'వోల్టేజ్ (V)',
      'updated': 'నవీకరించబడింది',
      'batteryCharge': 'బ్యాటరీ ఛార్జ్',
      'backupTime': 'అంచనా బ్యాకప్ సమయం',
      'usageHistory': 'మూలం వినియోగ చరిత్ర',
      'appearance': 'స్వరూపం',
      'darkMode': 'డార్క్ మోడ్',
      'language': 'భాష',
      'account': 'ఖాతా',
      'editProfile': 'ప్రొఫైల్ సవరించు',
      'changePassword': 'పాస్వర్డ్ మార్చు',
      'notifications': 'నోటిఫికేషన్ సెట్టింగులు',
      'about': 'గురించి',
      'appVersion': 'యాప్ వెర్షన్',
      'help': 'సహాయం మరియు మదద్',
      'privacy': 'గోప్యతా విధానం',
    },
    'mr': {
      'appTitle': 'क्लिनिक्स',
      'slogan': 'वीजपुरवठा खंडितासाठी अभियांत्रिकी, जीवनासाठी बांधले!',
      'selectRole': 'तुमची भूमिका निवडा',
      'admin': 'प्रशासक',
      'doctor': 'डॉक्टर',
      'nurse': 'नर्स',
      'technician': 'तंत्रज्ञ',
      'user': 'वापरकर्ता',
      'loginTitle': 'क्लिनिक्स लॉगिन',
      'username': 'वापरकर्तानाव',
      'password': 'पासवर्ड',
      'login': 'लॉग इन',
      'forgotPassword': 'पासवर्ड विसरलात?',
      'changeRole': 'भूमिका बदला',
      'haveAccount': 'आधीपासून खाते आहे? साइन इन',
      'dashboard': 'डॅशबोर्ड',
      'battery': 'बॅटरी',
      'logData': 'लॉग डेटा',
      'settings': 'सेटिंग्ज',
      'logout': 'लॉगआउट',
      'systemSettings': 'सिस्टम सेटिंग्ज',
      'sourceInUse': 'वापरातील स्रोत',
      'grid': 'ग्रिड',
      'voltage': 'व्होल्टेज (V)',
      'updated': 'अद्यतनित',
      'batteryCharge': 'बॅटरी चार्ज',
      'backupTime': 'अंदाजे बॅकअप वेळ',
      'usageHistory': 'स्रोत वापर इतिहास',
      'appearance': 'देखावा',
      'darkMode': 'डार्क मोड',
      'language': 'भाषा',
      'account': 'खाते',
      'editProfile': 'प्रोफाइल संपादित',
      'changePassword': 'पासवर्ड बदला',
      'notifications': 'अधिसूचना सेटिंग्ज',
      'about': 'विषयी',
      'appVersion': 'ॲप आवृत्ती',
      'help': 'मदत आणि समर्थन',
      'privacy': 'गोपनीयता धोरण',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']![key] ??
        key;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'hi', 'ta', 'te', 'mr', 'bn', 'gu', 'kn', 'ml', 'pa'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}